name: Watchdog job

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  watchdog:
    runs-on: ubuntu-latest
    environment: runner

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run watchdog
        env:
          REGD: ${{ secrets.REGD }}
          PASS: ${{ secrets.PASS }}
          VTOP_SEMID: ${{ secrets.VTOP_SEMID }}
          MAX_RETIRES: ${{ secrets.MAX_RETIRES }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          # REGD: ${{ vars.REGD }}
          # PASS: ${{ vars.PASS }}
          # VTOP_SEMID: ${{ vars.VTOP_SEMID }}
          # MAX_RETIRES: ${{ vars.MAX_RETIRES }}
          # TG_CHAT_ID: ${{ vars.TG_CHAT_ID }}
          # TG_BOT_TOKEN: ${{ vars.TG_BOT_TOKEN }}
        run: python main.py
